services:
  realtor-gpt-db:
    container_name: realtor-gpt-db
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - realtor-gpt-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    shm_size: 512mb

volumes:
  realtor-gpt-db-data:
